### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'put'

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#113]
Launching KoboldAI with the following options : python3 aiserver.py --model KoboldAI/fairseq-dense-13B-Janeway --colab
Initializing Flask...
Colab Check: True OK!
Starting webserver...
sending error to clients
Traceback (most recent call last):File "aiserver.py", line 10471, in <module> general_startup()File "aiserver.py", line 1048, in general_startup getattr(koboldai_vars, "_{}".format(setting)).from_json(settings_file.read())File "/content/KoboldAI-Client/koboldai_settings.py", line 365, in from_json setattr(self, key, bool(value))File "/content/KoboldAI-Client/koboldai_settings.py", line 798, in __setattr__ process_variable_changes(self.socketio, self.__class__.__name__.replace("_settings", ""), name, value, old_value)File "/content/KoboldAI-Client/koboldai_settings.py", line 38, in process_variable_changes queue.put(data)AttributeError: 'NoneType' object has no attribute 'put'

Starting Janeway 13B with the github link to new UI, deleting and getting another TPU instance lends the same result.

**Comment by ebolam** [comment]
Should be fixed now. Let me know if you encounter it again.
