### ISSUE TITLE
Exception in thread Thread-2: ImportError

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#121]
Starting webserver...
Welcome to KoboldAI!
You have selected the following Model: KoboldAI/fairseq-dense-13B-Janeway
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "aiserver.py", line 2529, in load_model
    import tpu_mtj_backend
  File "/content/KoboldAI-Client/tpu_mtj_backend.py", line 48, in <module>
    import optax
  File "/usr/local/lib/python3.7/dist-packages/optax/__init__.py", line 17, in <module>
    from optax._src.alias import adabelief
  File "/usr/local/lib/python3.7/dist-packages/optax/_src/alias.py", line 21, in <module>
    from optax._src import base
  File "/usr/local/lib/python3.7/dist-packages/optax/_src/base.py", line 18, in <module>
    import chex
  File "/usr/local/lib/python3.7/dist-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/usr/local/lib/python3.7/dist-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/usr/local/lib/python3.7/dist-packages/chex/_src/asserts_internal.py", line 36, in <module>
    from jax.experimental import checkify
ImportError: cannot import name 'checkify' from 'jax.experimental' (/usr/local/lib/python3.7/dist-packages/jax/experimental/__init__.py)

**Comment by ebolam** [comment]
Bug in united. It's being tracked there and will get fixed here once it's fixed there.
