### ISSUE TITLE
Options area for mobile is not hidden

### ISSUE THREAD

**Issue by LightSaveUs** [ebolam/KoboldAI#125]
The dummy area to keep the options area from showing up is half-hidden. It starts pulsating the moment you accidentally click on it.
It would be better to hide this pulsation and the area's half-hidden state in the Web version, so that this does not happen.

Error log:

Exception in thread Thread-72:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid,data[1:])
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/init.py", line 283, in _handler
    args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/init.py", line 826, in _handle_event
    ret = handler(args)
  File "aiserver.py", line 278, in g
    return f(*a, **k)
  File "aiserver.py", line 7222, in UI_2_Set_Selected_Text
    koboldai_vars.actions[int(data['id'])] = data['text']
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

![image](https://user-images.githubusercontent.com/108632621/190258280-494529e8-9dd7-4dc8-ae69-4ef7789a6bc2.png)

**Comment by ebolam** [comment]
I think this is fixed now. Let me know if you get it again
