### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#131]
Exception in thread Thread-679:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 278, in g
    return f(*a, **k)
  File "aiserver.py", line 7216, in UI_2_Set_Selected_Text
    koboldai_vars.actions[int(data['id'])] = data['text']
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

A rather strange one, it is rather hard to replicate at times, but usually it seems to manifest when trying to either drag saved outputs on the right, or to, somehow, drag something within the text itself during generation. Maybe it is related to the strange bug display? (text block, aka output/input, would remain blue indefinitely, as if selected, until another line is selected for editing.)

**Comment by ebolam** [comment]
I think this is fixed now. Let me know if you run across it again.
