### ISSUE TITLE
RuntimeError: Requested backend tpu_driver

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#141]
2022-09-19 04:49:15.281929: E external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/grpc_tpu_driver.cc:1070] Failed to open the gRPC driver: 4: Deadline Exceeded: 
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "aiserver.py", line 2831, in load_model
    tpu_mtj_backend.load_model(koboldai_vars.custmodpth, hf_checkpoint=koboldai_vars.model not in ("TPUMeshTransformerGPTJ", "TPUMeshTransformerGPTNeoX") and koboldai_vars.use_colab_tpu, **koboldai_vars.modelconfig)
  File "/content/KoboldAI-Client/tpu_mtj_backend.py", line 1179, in load_model
    devices = np.array(jax.devices()[:cores_per_replica]).reshape(mesh_shape)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/lib/xla_bridge.py", line 314, in devices
    return get_backend(backend).devices()
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/lib/xla_bridge.py", line 258, in get_backend
    return _get_backend_uncached(platform)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/lib/xla_bridge.py", line 248, in _get_backend_uncached
    raise RuntimeError(f"Requested backend {platform}, but it failed "
RuntimeError: Requested backend tpu_driver, but it failed to initialize: DEADLINE_EXCEEDED: Failed to connect to remote server at address: grpc://10.25.155.170:8470. Error from gRPC: Deadline Exceeded. Details: 

50/50 chance to trigger it seems, before the error popped up, timer for connection got stuck without anything happening for a minute or so.

**Comment by ebolam** [comment]
I think this is the TPU session getting stollen from Colab (IE they ran out of free resources). If not then this needs to go to the general united support as it'd be the general backend that's failing.
