### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#147]
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 484, in g
    return f(*a, **k)
  File "aiserver.py", line 8216, in UI_2_generate_image
    tpool.execute(generate_image_in_background)
  File "/usr/local/lib/python3.7/dist-packages/eventlet/tpool.py", line 132, in execute
    six.reraise(c, e, tb)
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/eventlet/tpool.py", line 86, in tworker
    rv = meth(*args, **kwargs)
  File "aiserver.py", line 8270, in generate_image_in_background
    summarizer = summary_pipeline(task="summarization", model=koboldai_vars.summarizer, tokenizer=koboldai_vars.summary_tokenizer, device=device)
  File "/usr/local/lib/python3.7/dist-packages/transformers/pipelines/__init__.py", line 767, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/pipelines/text2text_generation.py", line 47, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/pipelines/base.py", line 768, in __init__
    self.device = device if framework == "tf" else torch.device("cpu" if device < 0 else f"cuda:{device}")
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by MrXen0morph** [comment]
The error shows up if you attempt to generate an image, which prompts it to download model. Error message shows up right after the download is complete, with the 
/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py:624: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  FutureWarning,

**Comment by ebolam** [comment]
Just did a fix for this that seemed to fix db0. 

Note you still need to download stable diffusion if running local generation. You can set your image generation to horde using the image setting in the interface tab if you don't have it.
