### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#163]
Loading model tensors: 100%|█████████████████████████████████████| 645/645 [08:44<00:00,  1.23it/s]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "aiserver.py", line 2923, in load_model
    tpool.execute(tpu_mtj_backend.load_model(koboldai_vars.custmodpth, hf_checkpoint=koboldai_vars.model not in ("TPUMeshTransformerGPTJ", "TPUMeshTransformerGPTNeoX") and koboldai_vars.use_colab_tpu, **koboldai_vars.modelconfig))
  File "/usr/local/lib/python3.7/dist-packages/eventlet/tpool.py", line 132, in execute
    six.reraise(c, e, tb)
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/eventlet/tpool.py", line 86, in tworker
    rv = meth(*args, **kwargs)
TypeError: 'NoneType' object is not callable

**Comment by ebolam** [comment]
This is now fixed
