### ISSUE TITLE
ValueError: In-scope resources are insufficient to execute the xmapped function. The missing resources are: {'mp', 'dp'}

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#166]
Loading model tensors: 100%|█████████████████████████████████████| 645/645 [09:15<00:00,  1.16it/s]
INIT       | Starting   | LUA bridge
INIT       | OK         | LUA bridge
INIT       | Starting   | LUA Scripts
INIT       | OK         | LUA Scripts
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "aiserver.py", line 2962, in load_model
    final_startup()
  File "aiserver.py", line 7404, in final_startup
    soft_tokens = tpumtjgetsofttokens()
  File "aiserver.py", line 1416, in tpumtjgetsofttokens
    koboldai_vars.sp = tpu_mtj_backend.shard_xmap(tensor)
  File "/content/KoboldAI-Client/tpu_mtj_backend.py", line 128, in inner
    return xmap(x, np.empty(batch_dim))
  File "/usr/local/lib/python3.7/dist-packages/jax/experimental/maps.py", line 635, in fun_mapped
    fun_flat, args_flat, params, out_tree = infer_params(*args)
  File "/usr/local/lib/python3.7/dist-packages/jax/experimental/maps.py", line 569, in infer_params
    raise ValueError(f"In-scope resources are insufficient to execute the "
ValueError: In-scope resources are insufficient to execute the xmapped function. The missing resources are: {'mp', 'dp'}

**Comment by ebolam** [comment]
This is now fixed.
