### ISSUE TITLE
NameError on start up

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#247]
Initializing Mesh Transformer JAX, please wait...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "aiserver.py", line 3088, in load_model
    initial_load=initial_load, logger=logger, cloudflare=cloudflare,
NameError: name 'cloudflare' is not defined

**Comment by ebolam** [comment]
This should be fixed now.
