### ISSUE TITLE
Cloudflare error on Colab

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#248]
Hi Im getting this error in colab
-----
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "aiserver.py", line 3088, in load_model
    initial_load=initial_load, logger=logger, cloudflare=cloudflare,
NameError: name 'cloudflare' is not defined

**Comment by ebolam** [comment]
Should be fixed now
