### ISSUE TITLE
Alt-Multi Gen Error

### ISSUE THREAD

**Issue by ghost** [ebolam/KoboldAI#328]
Hi I believe Alt Multi-Gen is a way for the ai to generate one at a time to be able to allow multi generation for larger models for TPUs, like making it serialized rather than parallelized? I tried it with at least 2 generations on and I get an error. I attached a copy for reference. Thank you.
[Error.txt](https://github.com/ebolam/KoboldAI/files/10162807/Error.txt)

**Comment by ebolam** [comment]
Fixed now

**Comment by ghost** [comment]
@ebolam Now I'm getting this error 
ERROR      | __main__:generate:6223 - Traceback (most recent call last):
  File "aiserver.py", line 6210, in generate
    genout, already_generated = tpool.execute(core_generate, txt, minimum, maximum, found_entries)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/tpool.py", line 132, in execute
    six.reraise(c, e, tb)
  File "/usr/local/lib/python3.8/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/eventlet/tpool.py", line 86, in tworker
    rv = meth(*args, **kwargs)
  File "aiserver.py", line 5500, in core_generate
    total_gens = torch.cat((total_gens, genout))
TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray
