### ISSUE TITLE
UI Randomly Disconnects

### ISSUE THREAD

**Issue by GuiAworld** [ebolam/KoboldAI#33]
umm, The ui just randomly disconnects, after a while without any inputs.

log
```
loading D:/Games/KoboldAI/stories/sample_story_v2.json
Exception in thread Thread-24:
Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 6507, in UI_2_load_story
    loadRequest(file)
  File "aiserver.py", line 5459, in loadRequest
    loadJSON(js)
  File "aiserver.py", line 5468, in loadJSON
    load_story_v2(json_data)
  File "aiserver.py", line 5570, in load_story_v2
    koboldai_vars.load_story(session['story'], js)
  File "D:\Games\KoboldAI\koboldai_settings.py", line 85, in load_story
    self._story_settings[story_name].from_json(json_data)
  File "D:\Games\KoboldAI\koboldai_settings.py", line 330, in from_json
    getattr(self, key).load_json(value)
  File "D:\Games\KoboldAI\koboldai_settings.py", line 786, in load_json
    self.recalc_token_length()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 966, in recalc_token_length
    ignore = self.koboldai_vars.calc_ai_text()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 194, in calc_ai_text
    if self.actions.actions[i]["Selected Text Length"]+used_tokens <= token_budget and not used_all_tokens:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Exception in thread Thread-45:
Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 6577, in UI_2_delete_world_info
    koboldai_vars.worldinfo_v2.delete(int(uid))
  File "D:\Games\KoboldAI\koboldai_settings.py", line 1169, in delete
    del self.world_info[uid]
KeyError: -1
Joining Room UI_2
actions is of type <class 'koboldai_settings.KoboldStoryRegister'> and I can't transmit
message handler error
Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 762, in _handle_event
    ret = handler(auth)
TypeError: do_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\engineio\server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 776, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 668, in _handle_connect
    success = self._trigger_event(
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 764, in _handle_event
    ret = handler()
  File "aiserver.py", line 3013, in do_connect
    ui2_connect()
  File "aiserver.py", line 6005, in ui2_connect
    koboldai_vars.send_to_ui()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 116, in send_to_ui
    self._story_settings['default'].send_to_ui()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 340, in send_to_ui
    process_variable_changes(self.socketio, self.__class__.__name__.replace("_settings", ""), name, value, None)
  File "D:\Games\KoboldAI\koboldai_settings.py", line 41, in process_variable_changes
    socketio.emit("var_changed", {"classname": "actions", "name": "In AI Input", "old_value": None, "value": {"id": i, 'In AI Input': value.actions[i]['In AI Input']}}, include_self=True, broadcast=True, room="UI_2")
KeyError: 'In AI Input'
Joining Room UI_2
actions is of type <class 'koboldai_settings.KoboldStoryRegister'> and I can't transmit
message handler error
Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 762, in _handle_event
    ret = handler(auth)
TypeError: do_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\engineio\server.py", line 622, in _trigger_event
    return self.handlers[event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 776, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 668, in _handle_connect
    success = self._trigger_event(
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 764, in _handle_event
    ret = handler()
  File "aiserver.py", line 3013, in do_connect
    ui2_connect()
  File "aiserver.py", line 6005, in ui2_connect
    koboldai_vars.send_to_ui()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 116, in send_to_ui
    self._story_settings['default'].send_to_ui()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 340, in send_to_ui
    process_variable_changes(self.socketio, self.__class__.__name__.replace("_settings", ""), name, value, None)
  File "D:\Games\KoboldAI\koboldai_settings.py", line 41, in process_variable_changes
    socketio.emit("var_changed", {"classname": "actions", "name": "In AI Input", "old_value": None, "value": {"id": i, 'In AI Input': value.actions[i]['In AI Input']}}, include_self=True, broadcast=True, room="UI_2")
KeyError: 'In AI Input'
```

**Comment by GuiAworld** [comment]
btw, I says disconnected in the UI but it doesn't apply the desaturation filter

**Comment by ebolam** [comment]
I've done some fixes for this and think I've squashed the bugs. It's with a new calculation for tokens and text to go to the AI. It's done way faster in the backend then I was doing in javascript so...

Let me know if it's still broken
