### ISSUE TITLE
Changing top-k results in errors

### ISSUE THREAD

**Issue by one-some** [ebolam/KoboldAI#339]
```
ERROR      | __main__:generate:6257 - Traceback (most recent call last):
  File "aiserver.py", line 6244, in generate
    genout, already_generated = tpool.execute(core_generate, txt, minimum, maximum, found_entries)
  File "/home/somebody/miniconda3/envs/kobold/lib/python3.7/site-packages/eventlet/tpool.py", line 132, in execute
    six.reraise(c, e, tb)
  File "/home/somebody/miniconda3/envs/kobold/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/somebody/miniconda3/envs/kobold/lib/python3.7/site-packages/eventlet/tpool.py", line 86, in tworker
    rv = meth(*args, **kwargs)
  File "aiserver.py", line 5439, in core_generate
    is_core=True,
  File "aiserver.py", line 5666, in raw_generate
    gen_settings=gen_settings,
  File "aiserver.py", line 5763, in torch_raw_generate
    num_return_sequences=batch_count,
  File "/home/somebody/miniconda3/envs/kobold/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/somebody/miniconda3/envs/kobold/lib/python3.7/site-packages/transformers/generation_utils.py", line 1553, in generate
    **model_kwargs,
  File "aiserver.py", line 2370, in new_sample
    return new_sample.old_sample(self, *args, **kwargs)
  File "/home/somebody/miniconda3/envs/kobold/lib/python3.7/site-packages/transformers/generation_utils.py", line 2496, in sample
    next_token_scores = logits_warper(input_ids, next_token_scores)
  File "aiserver.py", line 2356, in __call__
    scores = self.__warper_list[k](input_ids, scores, *args, **kwargs)
  File "aiserver.py", line 2162, in new_call
    return old_call(self, *args, **kwargs)
  File "/home/somebody/miniconda3/envs/kobold/lib/python3.7/site-packages/transformers/generation_logits_process.py", line 233, in __call__
    indices_to_remove = scores < torch.topk(scores, top_k)[0][..., -1, None]
TypeError: topk(): argument 'k' (position 2) must be int, not float
```
as the error indicates, top-k is somehow ending up as a float, when it should always be an int

**Comment by ebolam** [comment]
Odd. the set code sets the data type to whatever is in the class, so unless something flat set it (not from the UI) then we'd get this issue... Not sure what'd do that though. Did you play with the simple mode? That MIGHT do it...

**Comment by one-some** [comment]
> Odd. the set code sets the data type to whatever is in the class, so unless something flat set it (not from the UI) then we'd get this issue... Not sure what'd do that though. Did you play with the simple mode? That MIGHT do it...

nope, think I messed around in united for a bit though. probably best way to work around this is to cast to int on load for certain parameters, ill see if i can figure out how to do that
