### ISSUE TITLE
World Info is broken

### ISSUE THREAD

**Issue by GuiAworld** [ebolam/KoboldAI#36]
```
OK! KoboldAI/fairseq-dense-125M pipeline created!00:01<00:00, 240.36it/s]
Initializing Lua Bridge... OK!
Loading Core Script
Exception in thread Thread-27:
Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 6474, in UI_2_load_model
    load_model(use_gpu=data['use_gpu'], gpu_layers=data['gpu_layers'], disk_layers=data['disk_layers'], online_model=data['online_model'])
  File "aiserver.py", line 2271, in load_model
    koboldai_vars.tokenizer = tokenizer
  File "D:\Games\KoboldAI\koboldai_settings.py", line 265, in __setattr__
    setattr(self._story_settings['default'].actions, name, value)
  File "D:\Games\KoboldAI\koboldai_settings.py", line 1015, in __setattr__
    self.recalc_token_length()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 973, in recalc_token_length
    ignore = self.koboldai_vars.calc_ai_text()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 120, in calc_ai_text
    self.worldinfo_v2.reset_used_in_game()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 1293, in reset_used_in_game
    if self.world_info[key]["used_in_game"] != constant:
NameError: name 'constant' is not defined
Using Option Text: {'chunk': '5', 'option': '0'}
Exception in thread Thread-28:
Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 6350, in UI_2_Set_Selected_Text
    koboldai_vars.actions.use_option(int(data['option']), action_step=int(data['chunk']))
  File "D:\Games\KoboldAI\koboldai_settings.py", line 908, in use_option
    ignore = self.koboldai_vars.calc_ai_text()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 120, in calc_ai_text
    self.worldinfo_v2.reset_used_in_game()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 1293, in reset_used_in_game
    if self.world_info[key]["used_in_game"] != constant:
NameError: name 'constant' is not defined
{'data': '', 'theme': ''}
doing normal input
Min:432, Max:511, Txt:Niko is a small red kobold.
Niko has yellow, reptilian eyes and a long, scaly tail.
Niko is hungry and looking to steal something to eat.

Niko is an Idiot
Niko the kobold stalked carefully down the alley, his small scaly figure obscured by a dusky cloak that fluttered lightly in the cold winter breeze. Holding up his tail to keep it from dragging in the dirty snow that covered the cobblestone, he waited patiently for the butcher to turn his attention from his stall so that he could pilfer his next meal: a tender-looking  chicken. He crouched just slightly as he neared the stall to ensure that no one was watching, not that anyone would be dumb enough to hassle a small kobold. What else was there for a lowly kobold to do in a city? All that Niko needed to know was where to find the chicken and then how to make off with it.

A soft thud caused Niko to quickly lift his head. Standing behind the stall where the butcher had been cutting his chicken,
[Author's note: Things are about to get crazy for poor Niko.]
 he saw a pair of large brown eyes that were bright and wide-eyed. They were both wearing dark clothing and appeared to have been wearing gloves. Niko was leaning forward to look at them.

"What's wrong?" Niko asked, his voice shaking.

"Nothing," Niko said. "I'm fine."

The two men smiled at him. "You're okay, I guess."

He lifted his head, looking back at the pair of brown eyes. The expression on their faces was quite different than it had been in the past.

"Well, you can't see anything. You're not sure what happened, but you should try to get your head around it." Niko said. "You might think I'm a bit crazy, but you're right."

"Don't worry, I'll try to get my head
 around this.

The following is a list of the most popular expressions with the word 'dance' in it. You can also look for other words which we have not found.

We are looking for an energetic, motivated and dedicated individual to join our team. Applicants must have experience working in a multi disciplinary environment and possess strong communication skills. You will be responsible for managing the
Exception in thread Thread-29:
Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 6371, in UI_2_submit
    actionsubmit(data['data'], actionmode=koboldai_vars.actionmode)
  File "aiserver.py", line 3703, in actionsubmit
    calcsubmit(data)
  File "aiserver.py", line 3948, in calcsubmit
    generate(subtxt, min, max, found_entries=found_entries)
  File "aiserver.py", line 4156, in generate
    genresult(genout[0]["generated_text"])
  File "aiserver.py", line 4191, in genresult
    koboldai_vars.actions.append(genout)
  File "D:\Games\KoboldAI\koboldai_settings.py", line 823, in append
    ignore = self.koboldai_vars.calc_ai_text()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 120, in calc_ai_text
    self.worldinfo_v2.reset_used_in_game()
  File "D:\Games\KoboldAI\koboldai_settings.py", line 1293, in reset_used_in_game
    if self.world_info[key]["used_in_game"] != constant:
NameError: name 'constant' is not defined
```

**Comment by ebolam** [comment]
Fixed in latest commit
