### ISSUE TITLE
Saving using (or loading) from download story button is Busted

### ISSUE THREAD

**Issue by candymint23** [ebolam/KoboldAI#363]
Hi there, looks like the kaistory file generated when you press "download story" is busted. It saves fine but doesn't load properly, instead generating this error.
______________________________________________________________________________________________

ERROR      | __main__:g:591 - An error has been caught in function 'g', process 'MainProcess' (6152), thread 'MainThread' (8464):
Traceback (most recent call last):

  File "B:\python\lib\site-packages\eventlet\green\thread.py", line 43, in __thread_body
    func(*args, **kwargs)
    │     │       └ {}
    │     └ ()
    └ <bound method Thread._bootstrap of <Thread(Thread-46, started daemon 2482198543872)>>

  File "B:\python\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function start_new_thread.<locals>.wrap_bootstrap_inner at 0x00000241EE7D9A60>
    └ <Thread(Thread-46, started daemon 2482198543872)>

  File "B:\python\lib\site-packages\eventlet\green\thread.py", line 64, in wrap_bootstrap_inner
    bootstrap_inner()
    └ <bound method Thread._bootstrap_inner of <Thread(Thread-46, started daemon 2482198543872)>>

  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000241E456EE50>
    └ <Thread(Thread-46, started daemon 2482198543872)>

  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-46, started daemon 2482198543872)>
    │    │        │    └ (<socketio.server.Server object at 0x00000241EE2DF8B0>, 'tcTnFM5qiLkuZAj3AAAB', '9FEKK_PJGpqokZuMAAAA', ['upload_file', {'fil...
    │    │        └ <Thread(Thread-46, started daemon 2482198543872)>
    │    └ <bound method Server._handle_event_internal of <socketio.server.Server object at 0x00000241EE2DF8B0>>
    └ <Thread(Thread-46, started daemon 2482198543872)>

  File "B:\python\lib\site-packages\socketio\server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        │      │              │        │          │     └ ['upload_file', {'filename': 'Princess Adventure Origin.kaistory', 'data': b'PK\x03\x04\x14\x00\x00\x00\x00\x00pD2V\xc8M\xb5+...
        │      │              │        │          └ 'tcTnFM5qiLkuZAj3AAAB'
        │      │              │        └ '/'
        │      │              └ ['upload_file', {'filename': 'Princess Adventure Origin.kaistory', 'data': b'PK\x03\x04\x14\x00\x00\x00\x00\x00pD2V\xc8M\xb5+...
        │      └ <function Server._trigger_event at 0x00000241ECC74670>
        └ <socketio.server.Server object at 0x00000241EE2DF8B0>

  File "B:\python\lib\site-packages\socketio\server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
           │    │        │          │       └ ('tcTnFM5qiLkuZAj3AAAB', {'filename': 'Princess Adventure Origin.kaistory', 'data': b'PK\x03\x04\x14\x00\x00\x00\x00\x00pD2V\...
           │    │        │          └ 'upload_file'
           │    │        └ '/'
           │    └ {'/': {'get_model_info': <function get_model_info at 0x00000241EE41D820>, 'OAI_Key_Update': <function get_oai_models at 0x000...
           └ <socketio.server.Server object at 0x00000241EE2DF8B0>

  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
           │    │             │        │        │          └ 'tcTnFM5qiLkuZAj3AAAB'
           │    │             │        │        └ '/'
           │    │             │        └ 'upload_file'
           │    │             └ <function upload_file at 0x00000241EE430820>
           │    └ <function SocketIO._handle_event at 0x00000241ED13D280>
           └ <flask_socketio.SocketIO object at 0x00000241EE2DF9A0>

  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 826, in _handle_event
    ret = handler(*args)
          │        └ ({'filename': 'Princess Adventure Origin.kaistory', 'data': b'PK\x03\x04\x14\x00\x00\x00\x00\x00pD2V\xc8M\xb5+`\xcf\x00\x00`\...
          └ <function upload_file at 0x00000241EE430820>

> File "aiserver.py", line 591, in g
    return f(*a, **k)
           │  │    └ {}
           │  └ ({'filename': 'Princess Adventure Origin.kaistory', 'data': b'PK\x03\x04\x14\x00\x00\x00\x00\x00pD2V\xc8M\xb5+`\xcf\x00\x00`\...
           └ <function upload_file at 0x00000241EE430430>

  File "aiserver.py", line 8072, in upload_file
    json_data = json.loads(data['data'].decode("utf-8"))
                │    │     └ {'filename': 'Princess Adventure Origin.kaistory', 'data': b'PK\x03\x04\x14\x00\x00\x00\x00\x00pD2V\xc8M\xb5+`\xcf\x00\x00`\x...
                │    └ <function loads at 0x00000241E1E85DC0>
                └ <module 'json' from 'B:\\python\\lib\\json\\__init__.py'>

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 14: invalid continuation byte

**Comment by candymint23** [comment]
[Princess Adventure Origin.zip](https://github.com/ebolam/KoboldAI/files/10462453/Princess.Adventure.Origin.zip)
Good day here is the save file as requested.

**Comment by candymint23** [comment]
[error.txt](https://github.com/ebolam/KoboldAI/files/10476532/error.txt)
Also this error

**Comment by candymint23** [comment]
Update: Looks like dragging the file works but I haven't had luck with using the "load from local", it produces the error indicated in the error.txt and "load from file" does nothing but copy the KAISTORY file to the KAI folder but is not detected/extracted.
