### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MrXen0morph** [ebolam/KoboldAI#373]
Colab Check: True
INFO       | __main__:general_startup:1479 - Running on Repo: https://github.com/ebolam/KoboldAI Branch: UI2
MESSAGE    | Welcome to KoboldAI!
MESSAGE    | You have selected the following Model: KoboldAI/GPT-NeoX-20B-Erebus
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
INIT       | OK         | Webserver

Downloading (…)lve/main/config.json: 100% 1.52k/1.52k [00:00<00:00, 132kB/s]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/content/KoboldAI-Client/aiserver.py", line 2803, in load_model
    model_config = AutoConfig.from_pretrained(koboldai_vars.custmodpth, revision=args.revision, cache_dir="cache")
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/configuration_auto.py", line 809, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py", line 644, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py", line 730, in _dict_from_json_file
    with open(json_file, "r", encoding="utf-8") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/models--KoboldAI--GPT-NeoX-20B-Erebus/snapshots/1a80940a290452af71caf17a8e520955eb338e0f/config.json'

Happens on startup.

**Comment by MrXen0morph** [comment]
Addendum, seems to happen both for NeoX 20B and Skein 20B as well... I suppose it is also the same for other models too?
