### ISSUE TITLE
Error when selecting model

### ISSUE THREAD

**Issue by GuiAworld** [ebolam/KoboldAI#50]
When selecting Fairseq-Dense 125M it doesn't show the layers option, and produces an error

```
{'model': 'fsdlist', 'menu': 'mainmenu', 'display_name': 'Untuned Fairseq Dense'}
{'model': 'KoboldAI/fairseq-dense-125M', 'menu': 'fsdlist', 'display_name': 'Fairseq Dense 125M'}
Exception in thread Thread-24:
Traceback (most recent call last):
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Games\KoboldAI\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\socketio\server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "D:\Games\KoboldAI\miniconda3\lib\site-packages\flask_socketio\__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 271, in g
    return f(*a, **k)
  File "aiserver.py", line 7127, in UI_2_load_model_button
    get_model_info(data['model'])
  File "aiserver.py", line 1345, in get_model_info
    break_values = [int(x) for x in break_values]
  File "aiserver.py", line 1345, in <listcomp>
    break_values = [int(x) for x in break_values]
ValueError: invalid literal for int() with base 10: ''
```

**Comment by ebolam** [comment]
Man, I can't get it to break. Can you send me your config.json for the model? I believe it's something different in that file compared to mine.

**Comment by ebolam** [comment]
I finally got it to error out on my part. Fix is in.
